name: backup

on:
  schedule:
    - cron: "1 0 * * *"
  workflow_run:
    workflows: ["main"]
    types:
      - completed

jobs:
  set-server:
      if: ${{ github.event.workflow_run.conclusion != 'success' }}
      runs-on: ubuntu-latest
      steps:
      - name: Install Chromium
        run: sudo apt-get install chromium-browser
      - name: Set CHROME_BIN
        run: export CHROME_BIN=/usr/bin/chromium-browser

  run-files:
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    needs: set-server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: node src/node/scrape.js
      - run: node src/node/horizons.js

      - name: Push changes
        run: |
          git config --global user.name 'HarisVidimlic19'
          git config --global user.email 'hvidimlic1234@hotmail.com' 
          git add .
          git commit -am "Automated data import"
          git push
