name: run-node-files-and-deploy

on:
  schedule:
    - cron: '1 0 * * *'

jobs:
  run-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: node ../src/js/scrape.js
      - run: node ../src/js/horizons.js
  deploy:
      runs-on: ubuntu-latest
      permissions: # Required if github_deployment is set to true.
        deployments: write
      steps:
          - uses: actions/checkout@v3
          - uses: JorgeLNJunior/render-deploy@v1.4.1
            with:
              service_id: ${{ secrets.RENDER_SERVICE_ID }} # required
              api_key: ${{ secrets.RENDER_API_KEY }} # required
              clear_cache: false # Clear build cache. Optional
              wait_deploy: false # Wait until the deploy status is successful. Warning! Free Render services can take +5 minutes to be fully deployed. Optional
              github_deployment: false # Create a GitHub deployment. Optional
              deployment_environment: 'production' # GitHub deployment enviroment name. Optional
              #github_token: ${{ secrets.GITHUB_TOKEN }} # Remove if github_deployment is false. Optional
